graph TD
    A[Operator Monitoring: Routine Checks, HMI Interaction] -->|Sensor Data| B[Data Collection - Monitoring: HRV, EEG, Eye-Tracking]
    B -->|Processed Data| C[Performance Analysis - Evaluating: Risk Score Generation]
    C -->|Alerts & Adjustments| D[Intervention: Managing, HMI Feedback, Task Support]
    D -->|Refined Parameters| A
    style A fill:#add8e6,stroke:#333,stroke-width:2px,color:#000
    style B fill:#add8e6,stroke:#333,stroke-width:2px,color:#000
    style C fill:#add8e6,stroke:#333,stroke-width:2px,color:#000
    style D fill:#add8e6,stroke:#333,stroke-width:2px,color:#000
    linkStyle 0,1,2,3 stroke:#0000ff,stroke-width:2px,color:#000
    linkStyle 3 stroke:#ff0000,stroke-width:2px,stroke-dasharray: 5,5